import { StoryItem, CitySummary } from '../types';

export async function fetchStoriesFromServer(): Promise<{
  stories: StoryItem[];
  summary: CitySummary;
  isAiActive: boolean;
}> {
  try {
    const res = await fetch('/api/stories');
    if (!res.ok) {
      throw new Error(`Server returned ${res.status}`);
    }
    const data = await res.json();
    return data;
  } catch (err) {
    console.warn('Direct server fetch failed, using fallback stories:', err);
    return getLocalFallbackStories();
  }
}

export function getLocalFallbackStories(): {
  stories: StoryItem[];
  summary: CitySummary;
  isAiActive: boolean;
} {
  const stories: StoryItem[] = [
    {
      id: 'fix-1',
      category: 'fix',
      fact: {
        id: 'fact-fix-1',
        category: 'fix',
        categoryLabel: 'FIX',
        emoji: '✨',
        datasetName: 'NYC 311 Service Requests',
        datasetId: 'erm2-nwe9',
        datasetUrl: 'https://data.cityofnewyork.us/Social-Services/311-Service-Requests-from-2010-to-Present/erm2-nwe9',
        dateBadge: 'TODAY',
        dateStr: new Date().toISOString(),
        isFreshToday: true,
        borough: 'QUEENS',
        locationName: '31-15 Broadway, Astoria',
        coordinates: { lat: 40.7612, lng: -73.9248 },
        subject: 'Street Light Out',
        type: 'Street Light Condition',
        agency: 'Department of Transportation',
        raw: {
          unique_key: '60192831',
          created_date: '2026-08-15T02:14:00.000',
          closed_date: '2026-08-15T08:30:00.000',
          agency: 'DOT',
          agency_name: 'Department of Transportation',
          complaint_type: 'Street Light Condition',
          descriptor: 'Street Light Out',
          incident_address: '31-15 BROADWAY',
          street_name: 'BROADWAY',
          city: 'ASTORIA',
          borough: 'QUEENS',
          status: 'Closed',
          resolution_description: 'The Department of Transportation inspected and repaired the luminaire fixture.',
          latitude: '40.7612',
          longitude: '-73.9248',
        },
      },
      line1: "Someone's walk home",
      line2: 'got a little brighter.',
      detail: 'A streetlight issue in Queens was closed out today.',
      isAiGenerated: true,
      generatedAt: new Date().toISOString(),
    },
    {
      id: 'gather-1',
      category: 'gather',
      fact: {
        id: 'fact-gather-1',
        category: 'gather',
        categoryLabel: 'GATHER',
        emoji: '🎵',
        datasetName: 'NYC Permitted Event Information',
        datasetId: 'bkfu-528j',
        datasetUrl: 'https://data.cityofnewyork.us/City-Government/NYC-Permitted-Event-Information/bkfu-528j',
        dateBadge: 'TODAY',
        dateStr: new Date().toISOString(),
        isFreshToday: true,
        borough: 'BROOKLYN',
        locationName: 'Prospect Park Bandshell',
        coordinates: { lat: 40.6629, lng: -73.9789 },
        subject: 'Sunset Acoustic Sessions',
        type: 'Special Event',
        agency: 'NYC Department of Parks & Recreation',
        raw: {
          event_id: '89102',
          event_name: 'Sunset Acoustic Sessions',
          event_type: 'Special Event',
          event_borough: 'Brooklyn',
          event_location: 'Prospect Park Bandshell',
          start_date_time: '2026-08-15T18:00:00.000',
          end_date_time: '2026-08-15T21:00:00.000',
          park_facility_name: 'Prospect Park',
          latitude: '40.6629',
          longitude: '-73.9789',
        },
      },
      line1: 'Where neighbors',
      line2: 'pulled up a lawn chair.',
      detail: 'An open music session brought people together in Prospect Park today.',
      isAiGenerated: true,
      generatedAt: new Date().toISOString(),
    },
    {
      id: 'create-1',
      category: 'create',
      fact: {
        id: 'fact-create-1',
        category: 'create',
        categoryLabel: 'CREATE',
        emoji: '🎬',
        datasetName: 'NYC Film Permits (MOME)',
        datasetId: 'tg4x-b46p',
        datasetUrl: 'https://data.cityofnewyork.us/City-Government/Film-Permits/tg4x-b46p',
        dateBadge: 'TODAY',
        dateStr: new Date().toISOString(),
        isFreshToday: true,
        borough: 'MANHATTAN',
        locationName: 'Perry Street & Bleecker St',
        coordinates: { lat: 40.7356, lng: -74.0048 },
        subject: 'Feature Film Shooting Permit',
        type: 'Shooting Permit',
        agency: "Mayor's Office of Media & Entertainment",
        raw: {
          eventid: '710294',
          eventtype: 'Shooting Permit',
          subcategoryname: 'Feature Film',
          borough: 'Manhattan',
          parkingheld: 'Perry Street & Bleecker St',
          startdatetime: '2026-08-15T06:00:00.000',
          enddatetime: '2026-08-15T20:00:00.000',
          categoryname: 'Film',
          latitude: '40.7356',
          longitude: '-74.0048',
        },
      },
      line1: 'A quiet West Village block',
      line2: "turned into a film set.",
      detail: 'Cameras rolled on Perry Street for an independent feature today.',
      isAiGenerated: true,
      generatedAt: new Date().toISOString(),
    },
    {
      id: 'care-1',
      category: 'care',
      fact: {
        id: 'fact-care-1',
        category: 'care',
        categoryLabel: 'CARE',
        emoji: '🐦',
        datasetName: 'Urban Park Ranger Animal Condition Response',
        datasetId: '8jbk-r428',
        datasetUrl: 'https://data.cityofnewyork.us/Environment/Urban-Park-Ranger-Animal-Condition-Response/8jbk-r428',
        dateBadge: 'ON RECORD',
        dateStr: '2026-06-12T14:30:00.000',
        isFreshToday: false,
        borough: 'BRONX',
        locationName: 'Van Cortlandt Park',
        coordinates: { lat: 40.8979, lng: -73.8860 },
        subject: 'Red-tailed Hawk',
        type: 'Monitored & Reunited with Nest',
        agency: 'Urban Park Rangers',
        raw: {
          animal_response_id: 'AR-2026-881',
          animal_class: 'Birds',
          species_description: 'Red-tailed Hawk',
          animal_condition: 'Healthy / Monitored & Reunited with Nest',
          borough: 'Bronx',
          property: 'Van Cortlandt Park',
          action_taken_by_ranger: 'Monitored juvenile raptor until safely returned to parent branch.',
          date_and_time_of_initial_call: '2026-06-12T14:30:00.000',
          latitude: '40.8979',
          longitude: '-73.8860',
        },
      },
      line1: 'A wild New Yorker',
      line2: 'got some help today.',
      detail: 'An Urban Park Ranger looked after a young red-tailed hawk in the Bronx.',
      isAiGenerated: true,
      generatedAt: new Date().toISOString(),
    },
    {
      id: 'fix-2',
      category: 'fix',
      fact: {
        id: 'fact-fix-2',
        category: 'fix',
        categoryLabel: 'FIX',
        emoji: '✨',
        datasetName: 'NYC 311 Service Requests',
        datasetId: 'erm2-nwe9',
        datasetUrl: 'https://data.cityofnewyork.us/Social-Services/311-Service-Requests-from-2010-to-Present/erm2-nwe9',
        dateBadge: 'TODAY',
        dateStr: new Date().toISOString(),
        isFreshToday: true,
        borough: 'BROOKLYN',
        locationName: 'Prospect Park West',
        coordinates: { lat: 40.6650, lng: -73.9760 },
        subject: 'Pothole Repaired',
        type: 'Street Condition',
        agency: 'Department of Transportation',
        raw: {
          unique_key: '60193910',
          created_date: '2026-08-15T04:10:00.000',
          closed_date: '2026-08-15T11:45:00.000',
          agency: 'DOT',
          agency_name: 'Department of Transportation',
          complaint_type: 'Street Condition',
          descriptor: 'Pothole Repaired',
          incident_address: 'PROSPECT PARK WEST',
          borough: 'BROOKLYN',
          status: 'Closed',
          resolution_description: 'The Department of Transportation repaired the roadway defect.',
          latitude: '40.6650',
          longitude: '-73.9760',
        },
      },
      line1: 'A morning bike ride',
      line2: 'got a little smoother.',
      detail: 'A roadway repair along Prospect Park West was completed today.',
      isAiGenerated: true,
      generatedAt: new Date().toISOString(),
    },
    {
      id: 'gather-2',
      category: 'gather',
      fact: {
        id: 'fact-gather-2',
        category: 'gather',
        categoryLabel: 'GATHER',
        emoji: '🎵',
        datasetName: 'NYC Permitted Event Information',
        datasetId: 'bkfu-528j',
        datasetUrl: 'https://data.cityofnewyork.us/City-Government/NYC-Permitted-Event-Information/bkfu-528j',
        dateBadge: 'TODAY',
        dateStr: new Date().toISOString(),
        isFreshToday: true,
        borough: 'MANHATTAN',
        locationName: 'Marcus Garvey Park',
        coordinates: { lat: 40.8048, lng: -73.9439 },
        subject: 'Harlem Community Garden Harvest Fair',
        type: 'Community Event',
        agency: 'NYC Department of Parks & Recreation',
        raw: {
          event_id: '89104',
          event_name: 'Community Garden Harvest Fair',
          event_type: 'Community Event',
          event_borough: 'Manhattan',
          event_location: 'Marcus Garvey Park Amphitheater',
          start_date_time: '2026-08-15T12:00:00.000',
          park_facility_name: 'Marcus Garvey Park',
          latitude: '40.8048',
          longitude: '-73.9439',
        },
      },
      line1: 'Fresh soil and laughter',
      line2: 'in the heart of Harlem.',
      detail: 'Neighbors gathered for a community harvest fair in Marcus Garvey Park.',
      isAiGenerated: true,
      generatedAt: new Date().toISOString(),
    },
    {
      id: 'create-2',
      category: 'create',
      fact: {
        id: 'fact-create-2',
        category: 'create',
        categoryLabel: 'CREATE',
        emoji: '🎬',
        datasetName: 'NYC Film Permits (MOME)',
        datasetId: 'tg4x-b46p',
        datasetUrl: 'https://data.cityofnewyork.us/City-Government/Film-Permits/tg4x-b46p',
        dateBadge: 'TODAY',
        dateStr: new Date().toISOString(),
        isFreshToday: true,
        borough: 'QUEENS',
        locationName: '48th Avenue & Vernon Blvd',
        coordinates: { lat: 40.7447, lng: -73.9535 },
        subject: 'Television Drama Shooting Permit',
        type: 'Shooting Permit',
        agency: "Mayor's Office of Media & Entertainment",
        raw: {
          eventid: '710301',
          eventtype: 'Shooting Permit',
          subcategoryname: 'Television Drama',
          borough: 'Queens',
          parkingheld: '48th Avenue & Vernon Blvd',
          startdatetime: '2026-08-15T07:00:00.000',
          categoryname: 'Television',
          latitude: '40.7447',
          longitude: '-73.9535',
        },
      },
      line1: 'The East River skyline',
      line2: 'framed a brand new scene.',
      detail: 'Long Island City hosted a television production shoot today.',
      isAiGenerated: true,
      generatedAt: new Date().toISOString(),
    },
    {
      id: 'care-2',
      category: 'care',
      fact: {
        id: 'fact-care-2',
        category: 'care',
        categoryLabel: 'CARE',
        emoji: '🐦',
        datasetName: 'Urban Park Ranger Animal Condition Response',
        datasetId: '8jbk-r428',
        datasetUrl: 'https://data.cityofnewyork.us/Environment/Urban-Park-Ranger-Animal-Condition-Response/8jbk-r428',
        dateBadge: 'ON RECORD',
        dateStr: '2026-05-20T10:15:00.000',
        isFreshToday: false,
        borough: 'MANHATTAN',
        locationName: 'Inwood Hill Park',
        coordinates: { lat: 40.8710, lng: -73.9260 },
        subject: 'Eastern Screech Owl',
        type: 'Relocated to Quiet Canopy',
        agency: 'Urban Park Rangers',
        raw: {
          animal_response_id: 'AR-2026-512',
          animal_class: 'Birds',
          species_description: 'Eastern Screech Owl',
          animal_condition: 'Uninjured / Relocated to Quiet Canopy',
          borough: 'Manhattan',
          property: 'Inwood Hill Park',
          action_taken_by_ranger: 'Assisted by Urban Park Rangers to higher safe perch away from pedestrian path.',
          date_and_time_of_initial_call: '2026-05-20T10:15:00.000',
          latitude: '40.8710',
          longitude: '-73.9260',
        },
      },
      line1: 'A quiet neighbor in the canopy',
      line2: 'found a peaceful branch.',
      detail: 'An Eastern screech owl was safely assisted by Rangers in Inwood Hill Park.',
      isAiGenerated: true,
      generatedAt: new Date().toISOString(),
    },
  ];

  const summary: CitySummary = {
    closed311Count: 14280,
    gatheringsCount: 184,
    filmsCount: 42,
    wildlifeRescuesCount: 18,
    lastUpdated: new Date().toLocaleTimeString('en-US', { hour: 'numeric', minute: '2-digit' }),
  };

  return { stories, summary, isAiActive: true };
}
